### ISSUE TITLE
Warning: Creating default object from empty value in views_handler_filter_selective->get_oids()

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/views_selective_filters#2]
On a D7 > Backdrop upgraded site, I'm seeing a warning message:
Warning: Creating default object from empty value in views_handler_filter_selective->get_oids() (line 318 of /[mysite]/web/modules/views_selective_filters/views/views_handler_filter_selective.inc).

The D7 module had the same issue reported at:
https://www.drupal.org/project/views_selective_filters/issues/3152283

with a proposed patch, committed to dev:
https://www.drupal.org/files/issues/2020-06-19/3152283-4-warning-object-from-empty-value-php-7.4.patch

I manually applied the proposed patch (2 lines of additional code) described there to the module on my dev site to see if it would work - and it did (at least, the warning went away).

The code change proposed applies to views_handler_filter_selective.inc:

```
@@ -268,6 +268,10 @@ class views_handler_filter_selective extends views_handler_filter_in_operator {
       if (!$view_copy) {
         return NULL;
       }
+
+      // Initialize display on the clone.
+      $view_copy->set_display($this->view->current_display);
+
       // Store a flag so that we can know from other places
       // that this view is being used to obtain selective data.
       $view_copy->selective_oids = TRUE;
```

I'm not smart enough to know what this is doing, nor if it has any unexpected effects in the Backdrop module. 

Assuming it to be ok, I'd like to recommend this patch to be applied and tested.

**Comment by nattywebdev** [comment]
#3 applied and I can confirm it fixes the problem for me.

**Comment by Wylbur** [comment]
Any chance of getting this fixed and into a new release?  This is breaking my site I just launched with PHP 8.2.
