### ISSUE TITLE
Co-maintain?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/views_selective_filters#7]
@bobchristenson I see you are seeking co-maintainers. If you're open to it, I'd be willing to co-maintain with you to help get a few of the fixes in and a new release. I am going to use this on a project and would like to get it to a slightly more updated/polished state.

**Comment by laryn** [comment]
I've made a PR so if you accept, you can just merge that in to make it official.

**Comment by bobchristenson** [comment]
Hey Laryn, just made you an admin :) I don't even remember doing this and I don't remember what this module even does :)  Feel free to do with it what you will!

**Comment by laryn** [comment]
@bobchristenson Thanks! Would you be willing to merge the linked PR just so we're following protocol on that?

https://github.com/backdrop-contrib/views_selective_filters/pull/8

**Comment by bobchristenson** [comment]
I’ve never done anything with a PR before so hopefully I did it correctly. :)

**Comment by laryn** [comment]
Well, now you have! 😄
